default: &default
  adapter: postgresql
  encoding: unicode
  pool: 10
  username: <%= ENV.fetch("DATABASE_USERNAME", "postgres") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD", "") %>

development:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME", "complexity_api_development") %>

test:
  <<: *default
  database: complexity_api_test

production:
  <<: *default
  database: complexity_api_production
